name: food_review
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest=8.1.1
  - pandas=2.2.1
  - seaborn=0.13.2
  - spacy=3.5.3
  - bs4=4.12.2
  - nltk=3.8.1
  - pip
  - pip:
    - contractions
    - azureml-core
    - azure-ai-ml