name: food_review
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest=8.1.1
  - pandas=2.2.1
  - seaborn=0.13.2
  - spacy=3.5.3
  - bs4=4.12.2
  - nltk=3.8.1
  - scikit-learn=1.4.2
  - xgboost=2.0.3
  - mlflow=2.12.1
  - pip
  - pip:
    - contractions==0.1.73
    - azureml-core
    - azure-ai-ml==1.15.0
    - textblob==0.18.0.post0
    - azureml-mlflow==1.56.0