name: CI

on:
  pull_request:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: food_review
          environment-file: environment.yml
          auto-activate-base: false

      
      # checking if the environment works well
      - run: |
          conda info
          conda list

      - name: Install Spacy module
        run: |
          python -m spacy download en_core_web_sm

      - name: Run tests
        run: |
          pytest tests


